config/routes.rb
Rails.application.routes.draw do
  resources :loans do
    collection do
      get :rejected
      get :open_loan

    end
    member do
      get :requested_loan
      get :pending_loan
    end
  end

  resources :wallets

  resources :users do
    member do
      post :confirm_loan
      post :reject_loan
    end
  end

  resources :sessions

  resources :admins  do
    collection do
      get :active_loans
      get :closed_loans
    end
    member do
      post :reject_loan
    end
  end

  root "users#home_page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  before_create :add_interest_rate

  belongs_to :user

  validates :amount, presence: true, numericality: true

  scope :requested, -> { where(state: "requested") }
  scope :closed_loans, ->(user_id) { where(user_id: user_id, state: "closed") }
  scope :requested_loans, ->(user_id) { where(user_id: user_id, state: "requested") }
  scope :pending_loans, ->(user_id) { where(user_id: user_id, state: "approved") }
  scope :open_loans, ->(user_id) { where(user_id: user_id, state: "open") }
  scope :rejected_loans, ->(user_id) { where(user_id: user_id, state: "rejected") }

  enum state: { requested: 'requested', approved: 'approved', open: 'open', closed: 'closed', rejected: 'rejected' }

  private

  def add_interest_rate
    self.interest_rate = 5.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password
  before_save { self.email = email.downcase }
  before_save { self.name =  name.titleize }
  after_create :create_wallet

  has_one :wallet, dependent: :destroy
  has_many :loans, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX, message: 'must be a valid email address' },
                    uniqueness: { case_sensitive: false }         
  validates :password, presence: true 

  private
  
  def create_wallet
    Wallet.create(user: self, balance: self.admin ? 1000000 : 10000)
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :require_user_logged_in
  before_action :check_admin

  def index
    @loans = Loan.requested
  end

  def edit
    @interest_rate = Loan.find(params[:id]).interest_rate
    respond_to do |format|
      format.js
    end
  end

  def update
    @loan = Loan.find(params[:id])
    if @loan.update(state: 'approved', approved_by_id: current_user.id,  interest_rate: params[:admin_interest_rate].present? ? params[:admin_interest_rate] : params[:interest_rate])
      redirect_to admins_path, flash: { notice: 'Loan Approved Sucessfully.' }
    else
      redirect_to root_path, flash: { notice: 'Something went wrong' }
    end
  end

  def reject_loan
    @loan = Loan.find(params[:id])
    if @loan.update(state: 'rejected', rejected_by_id: current_user.id)
      redirect_to admins_path, flash: { notice: 'Loan rejected.' }
    else
      redirect_to root_path, flash: { notice: 'Something went wrong, Unable to reject loan' }
    end
  end

  def active_loans
    @loans = Loan.where(state: "open")
  end

  def closed_loans
    @loans = Loan.where(state: "closed")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  rescue_from ActiveRecord::RecordNotFound, with: :not_found_method

  def not_found_method
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_admin
    redirect_to root_path, flash: { notice: 'You are not an admin' } unless @current_user&.admin?
  end

  def require_user_logged_in
    redirect_to new_session_path, flash: { notice: 'Kindly login' } if @current_user.nil?
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :require_user_logged_in

  def index
    @loans = Loan.closed_loans(current_user.id)
  end

  def new
    @loan = Loan.new
  end

  def create
    @loan =  Loan.new(loan_params)
    @loan.user_id = current_user.id
    if @loan.save
      redirect_to new_loan_path, flash: { notice: 'Loan request created.' }
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def requested_loan
    @loans = Loan.requested_loans(current_user.id)

  end

  def pending_loan
    @loans = Loan.pending_loans(current_user.id)
  end

  def open_loan
    @loans = Loan.open_loans(current_user.id)
  end

  def update
    @loan = Loan.find(params[:id])
    if current_user.wallet.balance >= @loan.amount
      current_user.wallet.update(balance: current_user.wallet.balance - @loan.amount)
      @user =  User.find_by(admin: true)
      @user.wallet.update(balance: @user.wallet.balance + @loan.amount)
      @loan.update(state: 'closed')
      redirect_to root_path, flash: { notice: 'Loan repaid successfully.' }
    else
      redirect_to root_path, flash: { notice: 'Insufficient balance to repay the loan.' }
    end
  end

  def rejected
    @loans = Loan.rejected_loans(current_user.id)

  end

  def destroy
    @loan = Loan.find_by(id: params[:id])
    @loan.destroy
    redirect_to root_path, flash: { notice: 'Loan deleted successfully.' }
  end

  private

  def loan_params
    params.require(:loan).permit(:amount)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), flash: { notice: 'Logged In Successfully' }
    else  
      flash[:notice] = 'Invalid Email or Password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { notice: 'Log Out Successfully' }
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: %i[ reject_loan confirm_loan show ]
  def index
  end

  def new
    @user  = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to new_session_path, flash: { notice: 'Sign up successfully' }
    else  
      flash[:notice] = 'Something went wrong'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @wallet_balance = @user.wallet.balance.to_i
    @open_loan = Loan.open_loans(current_user.id).count
    @closed_loan = Loan.closed_loans(current_user.id).count
  end

  def confirm_loan
    @loan = Loan.find(params[:id])
    @admin_user =  User.find_by(admin: true)
    if @loan.update(state: 'open') &&  @admin_user.wallet.balance >= @loan.amount
      @loan.user.wallet.update(balance: @loan.user.wallet.balance + @loan.amount)
      @admin_user.wallet.update(balance: @admin_user.wallet.balance - @loan.amount)
      InterestCalculatorJob.perform_async(@loan.id)
      DebitLoanJob.perform_async(@loan.id)
      redirect_to root_path, flash: { notice:  'Loan confirmed and amount credited to your wallet.' }
    end
  end

  def reject_loan
    @loan = Loan.find(params[:id])
    if @loan.update(state: 'rejected')
      redirect_to root_path, flash: { notice: 'Loan rejected.' }
    else
      redirect_to root_path, flash: { notice: 'Unable to reject loan.' }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def show_errors(object, field_name)
    return unless object.errors.any?
    return if object.errors.messages[field_name].blank?

    object.errors.messages[field_name].join(', ')
  end

end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/admins/active_loans.html.erb
<h1 class="text-center">Active Loans</h1>
<%= render partial: 'partials/loan_details', locals: { loans: @loans } %>

app/views/admins/closed_loans.html.erb
<h1 class="text-center">Closed Loans</h1>
<%= render partial: 'partials/loan_details', locals: { loans: @loans } %>

app/views/admins/edit.js.erb
$('body').find('#edit_loan_modal').remove();
$('body').append('<%= j (render "partials/edit_loan_modal") %>');
$('#edit_loan_modal').modal('show');

app/views/admins/index.html.erb
<h1 class="text-center">Requested Loans</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @loans.any? %>
        <div style="max-height: 450px; overflow-y: auto;">
          <table class="table table-striped table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Amount</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |loan| %>
                <tr>
                  <td><%= loan.amount %></td>
                  <td><%= loan.interest_rate %></td>
                  <td>
                    <div class="d-flex justify-content-center gap-3">
                      <%= link_to "Approve", edit_admin_path(loan.id), remote: true, class: "btn btn-link text-decoration-none text-reset btn-primary" %>
                      <%= button_to "Reject", reject_loan_admin_path(loan.id), class: "btn btn-link text-decoration-none text-reset btn-danger", data: { confirm: 'Are you sure?' } %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-center">No loans present</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LendMoney</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> 


    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'partials/navbar'%>
   <%= render 'partials/flash'%>
    <%= yield %>
    
  </body>
</html>

app/views/loans/index.html.erb
<h1 class="text-center">Settled Loans</h1>
<%= render partial: 'partials/loan_details', locals: { loans: @loans } %>

app/views/loans/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Loan Request</h1>
      <%= form_for @loan do |form|%>
        <div class="form-group">
          <%= form.label :Loan_Amount, class: 'required' %>
          <%= form.text_field :amount, class: "form-control", placeholder: "Enter the amount" , required: true%>
          <p class='error'><%= show_errors(@loan, :amount)%></p>
        </div>
        <p>Note: Default interest rate will be 5%, Admin can modify it</p>
        <%= form.submit "Request", class: " mt-3 button-design form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/loans/open_loan.html.erb
<h1 class="text-center">Open Loans</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @loans.any? %>
        <div style="max-height: 450px; overflow-y: auto;">
          <table class="table table-striped table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Amount</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |loan| %>
                <tr>
                  <td><%= loan.amount.to_i %></td>
                  <td><%= loan.interest_rate %>
                  </td>
                  <td><%= link_to "Pay All Amount", loan_path(loan.id), method: :put, class: "button-design text-decoration-none " %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-center">No loans present</p>
      <% end %>
    </div>
  </div>
</div>

app/views/loans/pending_loan.html.erb
<h1 class="text-center">Pending Loan</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @loans.any? %>
        <div style="max-height: 450px; overflow-y: auto;">
          <table class="table table-striped table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Amount</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |loan| %>
                <tr>
                  <td><%= loan.amount.to_i %></td>
                  <td><%= loan.interest_rate %></td>
                  <td>
                    <div class="d-flex justify-content-center">
                      <%= button_to "Confirm", confirm_loan_user_path(loan.id), remote: true, class: "btn btn-primary me-2" %>
                      <%= button_to "Reject", reject_loan_user_path(loan.id), class: "btn btn-danger" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-center">No loans present</p>
      <% end %>
    </div>
  </div>
</div>

app/views/loans/rejected.html.erb
<h1 class="text-center">Rejected Loans</h1>
<%= render partial: 'partials/loan_details', locals: { loans: @loans } %>

app/views/loans/requested_loan.html.erb
<h1 class="text-center">Requested Loans</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if @loans.any? %>
        <div style="max-height: 450px; overflow-y: auto;">
          <table class="table table-striped table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Amount</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Delete Request</th>
              </tr>
            </thead>
            <tbody>
              <% @loans.each do |loan| %>
                <tr>
                  <td><%= loan.amount %></td>
                  <td><%= loan.interest_rate %></td>
                  <td><%= button_to "Delete", loan_path(loan.id), method: :delete, class: "btn btn-link text-decoration-none text-reset button-design" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-center">No loans present</p>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_edit_loan_modal.html.erb
<div class="modal" tabindex="-1" id="edit_loan_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Interest Rate </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%# binding.pry %>
        <%= form_with url: admin_path(params[:id]), method: :patch do |form| %>
          <div class="form-group my-3">
            <%= form.label :interest_rate, 'Interest Rate' %>
            <%= form.number_field :admin_interest_rate, class: "form-control", placeholder: "Interest Rate" %>
          </div>
          <%= hidden_field_tag :interest_rate, @interest_rate %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= form.submit "Approve", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/partials/_flash.html.erb
<% if flash.notice %>
  <div class="modal flash-modal" id="flashModal" tabindex="-1" role="dialog" aria-labelledby="flashModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
      <div class="alert alert-success flash-message">
        <div class="text-center">
          <%= flash.notice %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function() {
  $('#flashModal').modal('show');
  setTimeout(function() {
    $('#flashModal').modal('hide');
  }, 2000);
});
  </script>

app/views/partials/_loan_details.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if loans.any? %>
        <div style="max-height: 450px; overflow-y: auto;">
          <table class="table table-striped table-bordered text-center">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Amount</th>
                <th scope="col">Interest Rate</th>
              </tr>
            </thead>
            <tbody>
              <% loans.each do |loan| %>
                <tr>
                  <td><%= loan.amount.to_i %></td>
                  <td><%= loan.interest_rate %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="text-center">No loans present</p>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mx-3">
  <div>
    <%= link_to root_path, class: "text-decoration-none text-reset" do %>
      <h3 >Lend Money</h3>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user.present? && !current_user.admin %>
        <li class="nav-item"> <%= link_to "Pending Loan", pending_loan_loan_path(current_user), class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Request Loan", new_loan_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Rejected Loan", rejected_loans_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Requested Loan", requested_loan_loan_path(current_user), class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Settled Loan", loans_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Open Loan", open_loan_loans_path, class: "nav-link" %></li>
      <% end %>
      <% if current_user.present? && current_user.admin %>
        <li class="nav-item"> <%= link_to "Requested Loans", admins_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Active Loans", active_loans_admins_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Closed Loans", closed_loans_admins_path, class: "nav-link" %></li>
      <% end %>
      <% if current_user.present?  %>
        <li class="nav-item"> <%= link_to "Profile", user_path(current_user),  class: "nav-link" %></li>
        <li class="nav-item"> <%= button_to "Logout", session_path(current_user), method: :delete, class: "btn btn-danger nav-link text-white" %></li>
      <% else %>
        <li class="nav-item"> <%= link_to "SignUp", new_user_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "LogIn", new_session_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/dashboard.html.erb
<h2> welcome for login </h2>

app/views/users/home_page.html.erb
<div class="centered-container">
  <%= image_tag 'home_page.jpg', alt: 'Home Page Image', class: 'background-image'  %>
</div>

<footer class="footer">
  Copyright @2024. All rights reserved!!
</footer>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Sign up</h1>
      <%= form_for @user, class: "my-form" do |form| %>
        <div class="form-group">
          <%= form.label :name, class: 'required' %>
          <%= form.text_field :name, class: "form-control", placeholder: "Enter Your Name" , required: true%>
          <p class='error'><%= show_errors(@user, :name) %></p>

        </div>
        <div class="form-group">
          <%= form.label :email, class: 'required' %>
          <%= form.email_field :email, class: "form-control", placeholder: "Enter Your Email", required: true%>
                    <p class='error'><%= show_errors(@user, :email) %></p>

        </div>
        <div class="form-group">
          <%= form.label :password, class: 'required' %>
          <%= form.password_field :password, class: "form-control", placeholder: "Enter Your Password", required: true%>
                    <p class='error'><%= show_errors(@user, :password) %></p>

        </div>
        <div class="form-group">
          <%= form.label :password_confirmation, class: 'required' %>
          <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Your Password", required: true%>
                    <p class='error'><%= show_errors(@user, :password_confirmation) %></p>

        </div>
        <%= link_to "Already an user? Login", new_session_path %>
        <%= form.submit "Sign Up", class: " mt-3 button-design form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Profile</h1>

      <div class="card">
        <div class="card-body text-center">
          <p>
            <strong>Name:</strong>
            <%= @user.name %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @user.email %>
          </p>

          <p>
            <strong>Wallet Balance:</strong>
            <%= @wallet_balance %>
          </p>
          <p>
            <strong>Open Loan:</strong>
            <%= @open_loan %>
          </p>
          <p>
            <strong>Close Loan:</strong>
            <%= @closed_loan %>
          </p>

        </div>
      </div>
    </div>
  </div>
</div>